window.esdocSearchIndex = [
  [
    "fastflux/core/observable/base~observable",
    "class/src/core/observable/base.js~Observable.html",
    "<span>Observable</span> <span class=\"search-result-import-path\">fastflux/core/observable/base</span>",
    "class"
  ],
  [
    "fastflux/core/observable/state~observablestate",
    "class/src/core/observable/state.js~ObservableState.html",
    "<span>ObservableState</span> <span class=\"search-result-import-path\">fastflux/core/observable/state</span>",
    "class"
  ],
  [
    "fastflux/core/store~store",
    "class/src/core/store.js~Store.html",
    "<span>Store</span> <span class=\"search-result-import-path\">fastflux/core/store</span>",
    "class"
  ],
  [
    "fastflux/core/observable/subscription~subscription",
    "class/src/core/observable/subscription.js~Subscription.html",
    "<span>Subscription</span> <span class=\"search-result-import-path\">fastflux/core/observable/subscription</span>",
    "class"
  ],
  [
    "fastflux/core/action~createaction",
    "function/index.html#static-function-createAction",
    "<span>createAction</span> <span class=\"search-result-import-path\">fastflux/core/action</span>",
    "function"
  ],
  [
    "fastflux/core/store~createstore",
    "function/index.html#static-function-createStore",
    "<span>createStore</span> <span class=\"search-result-import-path\">fastflux/core/store</span>",
    "function"
  ],
  [
    "fastflux/core/subscriber~createsubscriber",
    "function/index.html#static-function-createSubscriber",
    "<span>createSubscriber</span> <span class=\"search-result-import-path\">fastflux/core/subscriber</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/browser/fastflux.js",
    "file/src/browser/fastflux.js.html",
    "src/browser/fastflux.js",
    "file"
  ],
  [
    "src/core/action.js",
    "file/src/core/action.js.html",
    "src/core/action.js",
    "file"
  ],
  [
    "src/core/observable/base.js",
    "file/src/core/observable/base.js.html",
    "src/core/observable/base.js",
    "file"
  ],
  [
    "src/core/observable/base.js~observable#emit",
    "class/src/core/observable/base.js~Observable.html#instance-method-emit",
    "src/core/observable/base.js~Observable#emit",
    "method"
  ],
  [
    "src/core/observable/base.js~observable#filter",
    "class/src/core/observable/base.js~Observable.html#instance-method-filter",
    "src/core/observable/base.js~Observable#filter",
    "method"
  ],
  [
    "src/core/observable/base.js~observable#hassubscribed",
    "class/src/core/observable/base.js~Observable.html#instance-method-hasSubscribed",
    "src/core/observable/base.js~Observable#hasSubscribed",
    "method"
  ],
  [
    "src/core/observable/base.js~observable#map",
    "class/src/core/observable/base.js~Observable.html#instance-method-map",
    "src/core/observable/base.js~Observable#map",
    "method"
  ],
  [
    "src/core/observable/base.js~observable#reduce",
    "class/src/core/observable/base.js~Observable.html#instance-method-reduce",
    "src/core/observable/base.js~Observable#reduce",
    "method"
  ],
  [
    "src/core/observable/base.js~observable#subscribe",
    "class/src/core/observable/base.js~Observable.html#instance-method-subscribe",
    "src/core/observable/base.js~Observable#subscribe",
    "method"
  ],
  [
    "src/core/observable/base.js~observable#unsubscribe",
    "class/src/core/observable/base.js~Observable.html#instance-method-unsubscribe",
    "src/core/observable/base.js~Observable#unsubscribe",
    "method"
  ],
  [
    "src/core/observable/index.js",
    "file/src/core/observable/index.js.html",
    "src/core/observable/index.js",
    "file"
  ],
  [
    "src/core/observable/state.js",
    "file/src/core/observable/state.js.html",
    "src/core/observable/state.js",
    "file"
  ],
  [
    "src/core/observable/state.js~observablestate#constructor",
    "class/src/core/observable/state.js~ObservableState.html#instance-constructor-constructor",
    "src/core/observable/state.js~ObservableState#constructor",
    "method"
  ],
  [
    "src/core/observable/state.js~observablestate#emit",
    "class/src/core/observable/state.js~ObservableState.html#instance-method-emit",
    "src/core/observable/state.js~ObservableState#emit",
    "method"
  ],
  [
    "src/core/observable/state.js~observablestate#getstate",
    "class/src/core/observable/state.js~ObservableState.html#instance-method-getState",
    "src/core/observable/state.js~ObservableState#getState",
    "method"
  ],
  [
    "src/core/observable/subscription.js",
    "file/src/core/observable/subscription.js.html",
    "src/core/observable/subscription.js",
    "file"
  ],
  [
    "src/core/observable/subscription.js~subscription#activate",
    "class/src/core/observable/subscription.js~Subscription.html#instance-method-activate",
    "src/core/observable/subscription.js~Subscription#activate",
    "method"
  ],
  [
    "src/core/observable/subscription.js~subscription#constructor",
    "class/src/core/observable/subscription.js~Subscription.html#instance-constructor-constructor",
    "src/core/observable/subscription.js~Subscription#constructor",
    "method"
  ],
  [
    "src/core/observable/subscription.js~subscription#isactive",
    "class/src/core/observable/subscription.js~Subscription.html#instance-method-isActive",
    "src/core/observable/subscription.js~Subscription#isActive",
    "method"
  ],
  [
    "src/core/observable/subscription.js~subscription#terminate",
    "class/src/core/observable/subscription.js~Subscription.html#instance-method-terminate",
    "src/core/observable/subscription.js~Subscription#terminate",
    "method"
  ],
  [
    "src/core/store.js",
    "file/src/core/store.js.html",
    "src/core/store.js",
    "file"
  ],
  [
    "src/core/store.js~store#constructor",
    "class/src/core/store.js~Store.html#instance-constructor-constructor",
    "src/core/store.js~Store#constructor",
    "method"
  ],
  [
    "src/core/store.js~store#getinitialstate",
    "class/src/core/store.js~Store.html#instance-method-getInitialState",
    "src/core/store.js~Store#getInitialState",
    "method"
  ],
  [
    "src/core/store.js~store#send",
    "class/src/core/store.js~Store.html#instance-method-send",
    "src/core/store.js~Store#send",
    "method"
  ],
  [
    "src/core/subscriber.js",
    "file/src/core/subscriber.js.html",
    "src/core/subscriber.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~any",
    "typedef/index.html#static-typedef-Any",
    "src/index.js~Any",
    "typedef"
  ],
  [
    "src/index.js~message",
    "typedef/index.html#static-typedef-Message",
    "src/index.js~Message",
    "typedef"
  ],
  [
    "src/index.js~react.component",
    "external/index.html",
    "src/index.js~React.Component",
    "external"
  ],
  [
    "src/utils/index.js",
    "file/src/utils/index.js.html",
    "src/utils/index.js",
    "file"
  ]
]